### Check server health
GET {{api_host}}/health
Accept: application/json
Content-Type: application/json
Origin: http://localhost:3000

### Get OpenAPI specification
GET {{api_host}}/openapi
Accept: application/json

### Register a user
POST {{api_host}}/auth/register
Accept: application/json
Content-Type: application/json

{
  "email": "test",
  "password": "test",
  "username": "test"
}

### Login user
POST {{api_host}}/auth/login
Accept: application/json
Content-Type: application/json
Origin: some

{
  "email": "test",
  "password": "test"
}

### Get data from protected route
GET {{api_host}}/protected
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiM2I0NThiMTMtNmVkOS00YmJiLWIwYmUtZjUzNWFjMGMyZmYxIiwidXNlcm5hbWUiOiJ0ZXN0IiwiZXhwIjoxNzg0MjI4NjI2fQ.xguhdukorgCicEt6h0rFGh7KiZoOy8kN4pGt4hb3bbo