#!/bin/bash

. "./configs/bash/helpers"

printf "⚠️ Run pre-push checks\n\n"

# replace with make commands
#validate_commands "cargo check" "cargo clippy" "configs/scripts/cargo-fmt.sh" "cargo test" "cargo audit"